DROP INDEX PK_MEAL; -- 삭제

DROP TABLE MEAL CASCADE CONSTRAINTS; -- 삭제

CREATE TABLE MEAL (
    m_id VARCHAR2(20) NOT NULL, -- 회원아이디
    m_div CHAR(1) NOT NULL, -- 식사구분
    m_date CHAR(8 BYTE) NOT NULL, -- 날짜
    m_seq NUMBER(2, 0) NOT NULL, -- 입력순서
    f_code VARCHAR2(8) NOT NULL -- 식품코드
);

COMMENT ON TABLE MEAL IS '식사';

COMMENT ON COLUMN MEAL.m_id IS '회원아이디';

COMMENT ON COLUMN MEAL.m_div IS '식사구분';

COMMENT ON COLUMN MEAL.m_date IS '날짜';

COMMENT ON COLUMN MEAL.m_seq IS '입력순서';

COMMENT ON COLUMN MEAL.f_code IS '식품코드';

CREATE UNIQUE INDEX PK_MEAL
    ON MEAL (
        m_id ASC,
        m_div ASC,
        m_date ASC,
        m_seq ASC
    );

ALTER TABLE MEAL
ADD CONSTRAINT PK_MEAL
    PRIMARY KEY (
        m_id,
        m_div,
        m_date,
        m_seq
    );

ALTER TABLE MEAL
ADD CONSTRAINT FK_FOOD_TO_MEAL
    FOREIGN KEY (f_code)
    REFERENCES FOOD (f_code)
    ON DELETE CASCADE;
    
CREATE SEQUENCE M_SEQ_B START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE M_SEQ_L START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE M_SEQ_D START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE M_SEQ_S START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER M_SEQ_TRIGGER
BEFORE INSERT ON MEAL
FOR EACH ROW
BEGIN
  IF :NEW.m_div = 'B' THEN
    :NEW.m_seq := M_SEQ_B.NEXTVAL;
  ELSIF :NEW.m_div = 'L' THEN
    :NEW.m_seq := M_SEQ_L.NEXTVAL;
  ELSIF :NEW.m_div = 'D' THEN
    :NEW.m_seq := M_SEQ_D.NEXTVAL;
  ELSIF :NEW.m_div = 'S' THEN
    :NEW.m_seq := M_SEQ_S.NEXTVAL;
  END IF;
END;

COMMIT;